In [3]:
import numpy as np

arr = np.array((1, 2, 3))
print(arr)

[1 2 3]


In [4]:
print(arr)

[1 2 3]


In [9]:

a = np.array([[[1, 2, 3,], [4, 5, 6], [7, 8, 9]]])
print(a)

print(a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
brr = np.array([1, 2, 3, 4], ndmin = 5)

print(brr, brr.ndim)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3052750010.py, line 3)