In [3]:
import numpy as np

a = np. array([1, 2, 3, 4])
print(a[3])

b = np.array([5, 6, 7, 8])

print(a[0] + b[1])

4
7


    Access 2D arrays

In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

print(a2[1, 2])

6


    Access 3D Arrays

In [12]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a3)

print()
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

print(arr[0, 1, 2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
