In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a[2:])


# Slicing step
print(a[1:4:1])

[3 4]
[2 3 4]


In [11]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)
print(b[1, 1:3])

print(b[0:2 , 2:3])

[[1 2 3 4]
 [5 6 7 8]]
[6 7]
[[3]
 [7]]
