In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


# Creating Arrays With a Defined Data Type


In [9]:
b = np.array([1, 2, 3, 4], dtype = 'S')
print(b)
print(b.dtype)


c = np.array(['apple', 'banana', 'cherry'], dtype = 'S')
print(c)
print(c.dtype)

[b'1' b'2' b'3' b'4']
|S1
[b'apple' b'banana' b'cherry']
|S6


    change dtype on Existing Arrays

In [15]:
flt = np.array([1.3, 4.5, 6.0])
newflt = flt.astype('i')

print(newflt, newflt.dtype)

newflt1 = flt.astype(int)
print(newflt1, newflt1.dtype)

[1 4 6] int32
[1 4 6] int64


# Copy vs View

In [18]:
# Copy
d = np.array([1, 2, 3, 4])
e = d.copy()
e[2] = 321

print(d)
print(e)

# View
f = d.view()
f[0] = 43

print(d)
print(f)


print(e.base)
print(f.base)

[1 2 3 4]
[  1   2 321   4]
[43  2  3  4]
[43  2  3  4]
None
[43  2  3  4]


# Numpy Array Shape

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)

(2, 3)


In [22]:
y = np.array([1, 2, 3, 5], ndmin = 5)
print(y)
print("Shape of array", y.shape)

[[[[[1 2 3 5]]]]]
Shape of array (1, 1, 1, 1, 4)


# Array Reshaping

In [27]:
z1 = np.array([1, 2, 3, 4, 5, 6, 7, 8,9, 10, 11, 12])

# z2 = z1.reshape(3, 3)
# print(z2)

# 1D to 3-D
z3 = z1.reshape(2, 3, 2)
print(z3)

z4 = z3.reshape(-1)
print(z4)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]
