In [3]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)
    
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)
    
for x in arr:
    for y in x:
        print(y)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)
    
for x in arr:
    for y in x:
        print(y)

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [7]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types
    We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

    NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [11]:
brr = np.array([1, 2, 3])

for x in np.nditer(brr, flags=['buffered'], op_dtypes=['S']):
    print(x)
    

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [13]:
crr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, 1::2]):
    print(x)

3
4
7
8


In [14]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
