In [9]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print(np.concatenate((arr1, arr2)))

arr = np.stack((arr1, arr2), axis=2)
print(arr)

# Stacking Along Rows
arr = np.hstack((arr1, arr2))
print(arr)

# Stacking Along Columns
arr = np.vstack((arr1, arr2))


# Stacking Along Height (depth)
arr3 = np.array([1, 2, 3])

arr4 = np.array([4, 5, 6])
                
arr5 = np.dstack((arr3, arr4))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[1 4]
  [2 5]
  [3 6]]]


    Function	Stack Direction	Axis
    hstack()	Horizontally	axis=1
    vstack()	Vertically	axis=0
    dstack()	Depth	axis=2